name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build
        run: mvn --batch-mode --update-snapshots verify
      - run mkdir staging && cp target/*.jar staging/carrier-commander-`date "+%Y-%m-%d.jar`
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: staging/*.jar

